# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sonos:
  media_player:
    hosts:
      - 192.168.1.223

mqtt:
  sensor:
    - name: "TemperatureTankSensor"
      unique_id: "TemperatureTankSensor_001"
      state_topic: "TemperatureTank"
      device_class: temperature
      unit_of_measurement: "°C"
      expire_after: 15
    - name: "TemperatureRoofSensor"
      unique_id: "TemperatureRoofkSensor_001"
      state_topic: "TemperatureRoof"
      device_class: temperature
      unit_of_measurement: "°C"
      expire_after: 15
    - name: "SunCollectorPowerSensor"
      state_topic: "SunCollectorPower"
      device_class: power
      unit_of_measurement: "W"
      expire_after: 330
  number:
    - name: "Roof Offset"
      command_topic: "tempRoofOffsetByUser"
      state_topic: "RoofOffsetCurrent"
      min: -100
      max: 100
      step: 0.1
      mode: box
    - name: "Tank Offset"
      command_topic: "tempTankOffsetByUser"
      state_topic: "TankOffsetCurrent"
      min: -100
      max: 100
      step: 0.1
      mode: box
    - name: "Roof Reference Temperature"
      unique_id: "RoofReferenceTemperature_001"
      command_topic: "tempRoofReference"
      min: -20
      max: 120
      step: 0.1
      mode: box
    - name: "Tank Reference Temperature"
      unique_id: "TankReferenceTemperature_001"
      command_topic: "tempTankReference"
      min: -20
      max: 120
      step: 0.1
      mode: box

sensor:
  - platform: template
    sensors:
      suncollector_temperature_difference:
        friendly_name: "Temperature Difference between roof and tank"
        device_class: temperature
        unit_of_measurement: "C"
        value_template: "{{ states('sensor.temperatureroofsensor') | float - states('sensor.temperaturetanksensor') | float }}"

  - platform: integration
    source: sensor.suncollectorpowersensor
    name: suncollector_energy_produced
    unit_prefix: k
    round: 2
    max_sub_interval:
      minutes: 5
